name: Notificação no Discord

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Dependências
        working-directory: ./projeto
        run: npm install

      - name: Executar Testes Unitários
        working-directory: ./projeto
        run: npm test

      - name: Enviar alerta no Discord via Webhook
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "embeds": [{
                       "title": "🚀 Novo evento no Repositório!",
                       "color": 65280,
                       "fields": [
                         {"name": "Evento", "value": "'"${{ github.event_name }}"'", "inline": true},
                         {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
                         {"name": "Autor", "value": "'"${{ github.actor }}"'", "inline": true},
                         {"name": "Commit", "value": "'"${{ github.event.head_commit.message }}"'"}
                       ]
                     }]
                   }' \
               $DISCORD_WEBHOOK